# Generated by Django 4.1.7 on 2025-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='camra_id',
            field=models.CharField(blank=True, help_text='Official CAMRA IncID for this pub, if known', max_length=32, null=True, unique=True),
        ),
    ]
