version: v1-silver-dell-deploy
# yaml for google app engine settings
runtime: python39
instance_class: F1

entrypoint: gunicorn capstoneproject.wsgi:application --workers 3 --timeout 300

automatic_scaling:
  min_instances: 0
  max_instances: 1  # limited to control costs
  #target_cpu_utilization: 0.85  # Scale up when CPU reaches 65%


env_variables:
  DJANGO_SETTINGS_MODULE: "capstoneproject.settings"
  CLOUD_SQL_CONNECTION_NAME: "heritage-hunter-395913:europe-west2:pub-database-instance-1" # Use this standard variable
  DB_NAME: "postgres"
  USE_GOOGLE_CLOUD: 'True'
  DJANGO_DEBUG: 'False'
  #SOCIAL_AUTH_REDIRECT_URI: 'https://heritage-hunter-395913.nw.r.appspot.com/accounts/microsoft/login/callback/'


beta_settings:
  cloud_sql_instances: "heritage-hunter-395913:europe-west2:pub-database-instance-1"


# [START handlers]
handlers:
  # 1) Serve static files
- url: /static
  static_dir: staticfiles/

  # 2) Cron endpoint (only accessible by App Engine itself / admins)
- url: /tasks/cron/.*
  script: auto
  login: admin

  # 3) All other URLs go to Django
- url: /.*
  script: auto
